[package]
name = "roller"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"

[dependencies]
prost = "0.6"
async-std = "1.4"

[build-dependencies]
prost-build = { version = "0.6" }
