[package]
name = "roller"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"

[dependencies]
async-std = { version = "*", features = ["attributes", "unstable"] }
serde = { version = "*", features = ["derive"] }
toml = "*"
coremidi = "*"
futures = "*"
palette = "*"
ola_client = {path = "../ola_client"}
rustc-hash = "*"
derive_more = "*"
indexmap = "*"
itertools = "*"
ordered-float = "*"
num-traits = "*"
num-derive = "*"
