[package]
name = "roller"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"

[dependencies]
async-std = { version = "1.5", features = ["attributes", "unstable"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.6"
rimd = { git = "https://github.com/RustAudio/rimd.git" }
coremidi = "0.4.0"
futures = "0.3.1"
palette = "0.5.0"
ola_client = {path = "../ola_client"}
rustc-hash = "1.0"
derive_more = "0.99"
indexmap = "1.3"
itertools = "*"
