[package]
name = "ola_client"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"

[dependencies]
prost = "*"
async-std = { version = "*", features = ["attributes", "unstable"] }

[build-dependencies]
prost-build = { version = "*" }
