[package]
name = "ola_client"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]
edition = "2018"

[dependencies]
prost = "0.6"
async-std = { version = "1.5", features = ["attributes", "unstable"] }

[build-dependencies]
prost-build = { version = "0.6" }
