slug = "ave_quad_pro_flat_4ch"
label = "AVE Quad Pro Flat 4ch"
channel_count = 4
supported_effects = ["color", "dimmer"]

[[channels]]
channel = 1
parameter = "red"

[[channels]]
channel = 2
parameter = "green"

[[channels]]
channel = 3
parameter = "blue"

[[channels]]
channel = 4
parameter = "cool_white"
