slug = "mini_led_moving_head"
label = "Mini LED Moving Head"
channel_count = 14
channels = [
    "pan",
    "unused", # pan fine
    "tilt",
    "unused", # tilt fine
    "unused", # x/y speed
    "dimmer",
    "red",
    "green",
    "blue",
    "cool_white",
    "unused",
    "unused",
    "unused",
    "unused",
]
